spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: invitation
    password: 1234
    url: jdbc:postgresql://postgres-compose:5432/invitation
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://postgres-compose:5432/invitation?createDatabaseIfNotExist=true
    user: invitation
    password: 1234
    schemas:
      - invitation

jwt:
  secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
  expiration: 86400000