spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: invitation
    password: 1234
    url: jdbc:postgresql://localhost:5432/invitation
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/invitation?createDatabaseIfNotExist=true
    user: invitation
    password: 1234
    schemas:
      - invitation