spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    username: invitation
    password: 1234
    url: jdbc:postgresql://db:5432/invitation
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://db:5432/invitation?createDatabaseIfNotExist=true
    user: invitation
    password: 1234
    schemas:
      - invitation