version: '3'

services:
  invitation-ui-compose:
    image: node:14
    ports:
      - '3000:3000'
    volumes:
      - ./:/srv/react-docker
    working_dir: /srv/react-docker
    command: 'npm start'